# Generated by Django 5.0.7 on 2024-07-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanmembers',
            name='attacked_in_current_war',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clanmembers',
            name='stars_in_current_war',
            field=models.IntegerField(default=0),
        ),
    ]
