# Generated by Django 5.0.7 on 2024-07-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0003_clanmembers_participating_in_current_war'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanmembers',
            name='attacks_used',
            field=models.IntegerField(default=0),
        ),
    ]
