# Generated by Django 5.0.7 on 2024-07-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0004_clanmembers_attacks_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanmembers',
            name='war_participations',
            field=models.IntegerField(default=0),
        ),
    ]
